#!/bin/sh

# Create a video from the frames that were saved using P5 saveFrame

set -o errexit

# The name to the MP3 file that should be used as the audio track for the video.
mp3_path="$1"

# The directory which contains the saved frames.
input_d="${2:-$HOME/Downloads}"

if test -z "$mp3_path" -o -z "$input_d"
then
    echo "usage: `basename $0` input-mp3-name <directory-with-pngs>"
    exit 1
fi

set -o xtrace

# The name of the project. Derive this from the name of the MP3 file.
mp3_filename=$(basename "${mp3_path}")
name="${mp3_filename%%.*}"

# Change file extension from .mp3 to .mp4
output="${name}.mp4"

# Output directory in which to place / consolidate everything.
# output_d="$name-$(date '+%s')"
output_d="$name"

cd "$input_d"
mkdir -p "$output_d"
# We might've already moved the files, so ignore any errors. This way, we can
# rerun this script to regenerate the video without necessarily creating new
# source frames.
mv canvas-*.png "$output_d" || true
cd "$output_d"

ffmpeg -framerate 60 -pattern_type glob -i '*.png' \
    -codec:v libx264 \
    "$output"
