export const ignoredWords: string[] = [
    "the",
    "it",
    "a",
    "an",
    "this",
    "that",
    "and",
];

export const quotes: string[] = [
    "You are born free",
    `I’d only ever heard pop music on the radio and watched films on TV with straight narratives, so it blew my mind to see him tear up text and rearrange it. I didn’t start picking up a camera and cutting up film, it just made me think differently about how we can rearrange or decontextualise anything: words, visuals or sound.`,
    "The future is yet to come",
    "Like with any project that feels daunting, break it into ridiculously small pieces and start with the simplest one.",
    "I felt that pressure of time that is perhaps the surest indication we have left childhood behind.",
    "8 bits to me feels like a golden age of being able to fully comprehend a computer: limited opcode space, constrained yet powerful.",
    "Boredom is an emotion that a person would get past eventually.",
    "You can observe a lot by watching.",
    "There are some who are restrained in their desire for self-satisfaction, money, respect, power and status, and they genuinely focus on the craft itself, taking a genuine interest in it and losing themselves in the flow. Anything in themselves that might hinder this is examined and discarded if necessary, and possible.",
    "It is a presumption that the universe has to follow logic.",
    "Pattern recognition in higher dimensions",
    "Keep going. Don’t worry about everything else. Just keep going.",
    "Don't think about making art, just make it. Let everyone else decide if it's good or bad, whether they love it or hate it. While they decide, make more.",
    `Gravitational waves stretch and compress space itself. Humans have no sensory organs attuned to these waves. Instead, we have Laser Interferometer Gravitational-wave Observatories (LIGOs), which send twin beams of light across two vacuum chambers, each 4 km long and orthogonal to each other. Gravitational wave effects are observed by measuring the differences between the beams at the scale of 10,000th the diameter of an atomic nucleus.`,
    "The search for the basis of depression in chemistry might be committing a category error, mistaking the trouble in the mind for trouble in the brain, like opening the hood of a computer when a piece of software crashes.",
    "Gradually, and then all at once.",
    `Much of what people do is for regulating or soothing their feelings. I think this comes first, you know when you're not regulated and calmed down, not much else matters really. You need to get there before you can do just about anything. Well, you could still perform in a "dysregulated" condition, it's just a lot harder behaving sensibly when you are upset. Rule #1 - DON'T PANIC`,
    "To exist is to be consistent with oneself",
    `My work itself is the experiment, rather than the more common practice of exploring/experimenting before the work, with the composition appearing as a statement or answer, or at least provisional conclusion.`,
    "A throw of the dice will never abolish chance",
    `Concretization is an attempt to reduce uncertainity, which we abhor. But when we concretize something, we close it off to life, and it ceases to unfold in ways that are alive.`,
    `Experiments in the arts seem to negate the possibility of revision, as such. Any compositional action that might be seen as an effort to improve or refine the outcome is an independent experience, an independent experiment, an independent process. Experiments thus need to be self-contained, closed at a local level, but open globally to larger trajectories of development or exploration that go beyond the limits of any individual works.`,
    `Better would be to increase motivation, focus, enthusiasm, aliveness, and energy over time. Most people are trying to solve for the wrong problem: doing more stuff. Getting more things done. But if you do more things in a way that burns yourself out, that is ultimately low productivity over time.`,
    `Sit quietly and rub two fingers together for 30 seconds. Focus on the sensation - each and every texture and ridge.`,
    `I hope everyone can lead meaningful lives and do whatever that makes them happy, because after all, it is YOUR life. Not all of us have to become doctors, lawyers, wealthy businesspersons, or get married to be happy. I just wish I could say this to my late friend.`,
    `Thoughts are distinct from consciousness – you cannot steer your thoughts anymore that you can dictate what noise your ears will hear next. There seems to be a random process going on, totally un-called-for thoughts entering your consciousness. Sometimes a thought pops up, and comes an adjunct of other bodily feelings. So it seems as if the arising of thoughts is connected with the physical body on some level. The same goes for emotions.`,
    `Shaping the outputs of a random number generator is a great way of getting into new territory, but so is just working with the material (whether clay or code) and seeing where it takes you. It is all just a creative feedback loop.`,
    `Why repeat the past?`,
    `It is a misunderstanding of creativity that creators are geniuses that are projecting from a perfect world of ideas into reality. But what really happens with making is that we start making something, but then respond to the material, and end up with something quite different that our original idea.`,
    `The emergence of live coding was in part a reaction against “generative art”, in particular the idea that by using random numbers, we can create infinite variation, and gasp at the creative system we’ve made that hods a mirror to the beauty of the system. The problem is that the more we listen to infinite variation, the more it sounds the same.`,
    `It is not worthwhile to think of what you haven't or could have done. The best we can do is to enjoy the present moment.`,
    `A curve is not composed of points, it is a law that points obey, or again, a law according to which points can be constructed.`,
    `Some artists simply surrender to the unconscious.`,
    `In this distorted view, there's still belief in the dichotomy of self and others (and therefore the lack of others is experienced as loneliness), and the passing of time (and therefore the loneliness lasting forever). Both time and self are still division, while the truth is more fundamental than any division. I think the recognition of this truth is hellish to the extent that you still cling to division, and blissful to the extent that you can let go of it. To interpret an infinite consciousness as lonely is still to project your separateness from everything else.`,
    `...he says to me, "Are you ready to be yourself again?" I said, "Which one?"`,
    "Do something again and again from morning till evening, and to dream of it at night, and to think of nothing else than doing this well, as well as I alone can. When one lives this way, one thing after another that does not belong to such a life drops off, without hate or reluctance. What we do should determine what we forego.",
    "Never approach stories one at a time. If one writes a story at time, one can end up writing the same story until one dies. It is best to write them three, or five at a time. More if you have the energy. Don't write two at a time either: their interplay, like lovers' mirrors,  produces melancholy.",
    "If one says 'red' and there are 50 people listening, one can be sure that there will arise 50 different reds in the 50 different minds",
    "Maybe they have to be crazy. How else can you stare at an empty canvas and see a work of art?",
    "There is no medium that cannot serve art",
    "People misinterpret complexity as sophistication, which is baffling – the incomprehensible should cause suspicion rather than admiration",
    "You can only connect the dots looking backwards; believing that the dots will connect down the road will give you the confidence you need to follow your heart",
    "“If today were the last day of my life, would I want to do what I am about to do today?” And whenever the answer has been “No” for too many days in a row, I know I need to change something",
    "Look up and wonder, who else dreams on distant worlds, under the same stars?",
    "Do not go gentle into that good night. Rage, rage against the dying of the light.",
    "If philosophy is based on reason and rationality, then why is there so much disagreement?",
    "The world is so big and I am so small; but the wonder is that I can be myself",
    "A Deepness in The Sky",
    "Tomorrow on a million moons, a million suns will rise.",
    "Thinking that the entire world is rational and comprehensible is effectively the same thing as believing in god.",
    "They do not suffer less because they have no words",
    "Now that you don't have to be perfect, you can be good",
    "The only will there is is the will of God. The lack of free will is not a problem, for it aligns us with the will of God. Individual free will must be transcended in order to align with God.",
    "A poem is never finished, only abandoned",
    "It is not our youth but our childhood we should be worried of losing about",
    "What nursing has to do is to put the patient in the best condition for nature to act upon him",
    "A distorted and unstable self-image or sense of self",
    "All invitations must proceed from heaven perhaps",
    "It is never too late to be what you might have been",
    "At last, he loses his identity",
    "A momentary stay against confusion",
    "The reward of a thing well done is to have done it",
    "The end of life is not knowledge but action",
    `"yet" is such a hopeful word`,
    "Keeping it in your head until it writes itself down without your interference",
    "All sorts of things we think matter don't, she said, so long as you don't wake up in the morning with no hope in you.",
    "All achievement is a bondage",
    "It is dark because you are trying to hard. Lightly child, lightly. Learn to do everything lightly.",
];
