export const ignoredWords: string[] = [
    "the",
    "it",
    "a",
    "an",
    "this",
    "that",
    "and",
];

export const quotes: string[] = [
    "Chaos is a ladder",
    "You are born free",
    `I’d only ever heard pop music on the radio and watched films on TV with straight narratives, so it blew my mind to see how Gysin would tear up text and rearrange it. It blew the doors open in terms of the possibilities, but I didn’t start picking up a camera and cutting up film, it just made me think differently about how you can rearrange or decontextualise anything, whether related to visuals or sound.`,
    "The future is yet to come",
    "There is no time, really. Punctuality, however, is your personal responsibility.",
    "Like with any project that feels daunting, break it into ridiculously small pieces and start with the simplest one.",
    "I felt that pressure of time that is perhaps the surest indication we have left childhood behind.",
    "8 bits to me feels like a golden age of being able to fully comprehend a computer: limited opcode space, constrained yet powerful.",
    "I am glad when someone has one of my ideas, for it shows that I am on the right track.",
    "Intuition is another name for familiarity.",
    "Boredom is an emotion that a person would get past eventually.",
    "You can observe a lot by watching.",
    "Two weeks in another city",
    "There are some who are restrained in their desire for self-satisfaction, money, respect, power and status, and they genuinely focus on the craft itself, taking a genuine interest in it and losing themselves in the flow. Anything in themselves that might hinder this is examined and discarded if necessary/possible.",
    "It is a presumption that the universe has to follow logic.",
    "It must be true. If it were not true, no one would have the imagination to invent it.",
    "I think that chirp triggered the curiosity and imagination of people. While images are very powerful, sound is more engaging.",
    "Pattern recognition in higher dimensions",
    "Be curious, not judgmental. We are learning together.",
    "Keep going. Don’t worry about everything else. Just keep going.",
    "Don't think about making art, just get it done. Let everyone else decide if it's good or bad, whether they love it or hate it. While they decide, make more art.",
    `The formulation "we evolved an upright posture so that we could run more efficiently" is wrong. There was never any intention behind those changes - past ancestors whose posture happened to be more upright were more frequently successful in passing on their genes. But it never had some intended outcome, it just happened to be what worked best in the past. It says absolutely nothing about whether that is best for people in the present or future.`,
    `Gravitational waves stretch and compress space itself. Humans have no sensory organs attuned to these waves. Instead, we have Laser Interferometer Gravitational-wave Observatories (LIGOs), which send twin beams of light across two vacuum chambers, each 4 km long and orthogonal to each other. Gravitational wave effects are observed by measuring the differences between the beams at the scale of 10,000th the diameter of an atomic nucleus.`,
    "But like, ideas aren't germs and can't infect you. You have to choose to incorporate it using your knowledge system.",
    "Did the German finetuning reduce their capabilities? I've always been of the opinion that specialized models won't be as good as generalists because - like with our human brains - there are so many obscure connections between neurons that it's not as easy as leaving out unrelated information to get better at a specific topic (yes, Japanese poetry and Chinese cooking recipes could very well improve our Python coding models).",
    "For some, the search for the brain basis of depression in chemistry might be committing a category error, mistaking the trouble in the mind for trouble in the brain, like opening the hood of a computer when a piece of software crashes.",
    "The sky above the port was the color of television, tuned to a dead channel.",
    "Gradually, and then all at once.",
    `Much of what people do is for regulating or soothing their feelings. I think this comes first, you know when you're not regulated and calmed down, not much else matters really. You need to get there before you can do just about anything. Well, you could still perform in a "dysregulated" condition, it's just a lot harder behaving sensibly when you are upset. Rule #1 - DON'T PANIC`,
    "To exist is to be consistent with oneself",
    "Fantastic Beasts and Where to Find Them",
    `What has been central to my work is the fact that the work itself is the experiment, rather than what seems to me to be a more common practice of exploring/experimenting before the work, with the composition appearing as a statement or answer or at least provisional conclusion.`,
    "A throw of the dice will never abolish chance",
    `"He was unwilling to commit," Taravangian said. "He wasn't seeking justice, but to assuage his own conscience."`,
    `Concretization is an attempt to reduce uncertainity, which we abhor. But when we concretize something, we close it off to life, and it ceases to unfold in ways that are alive.`,
    `Move faster. Slowness anywhere justifies slowness everywhere. 2023 instead of 2024. This week instead of next week. Today instead of tomorrow. Moving fast compounds so much more than people realise`,
    `Art is an effort to explore uncharted territory`,
    `Experiments in the arts seem to negate the possibility of revision, as such. Any compositional action that might be seen as an effort to improve or refine the outcome is an independent experience, an independent experiment, an independent process. Experiments thus need to be self-contained, closed at a local level, but open globally to larger trajectories of development or exploration that go beyond the limits of any individual works.`,
    `Better would be to increase motivation, focus, enthusiasm, aliveness, and energy over time. Most people are trying to solve for the wrong problem: doing more stuff. Getting more things done. But if you do more things in a way that burns yourself out, that is ultimately low productivity over time.`,
    `Music for restless minds`,
    `Sit quietly and rub two fingers together for 30 seconds. Focus on the sensation - each and every texture and ridge.`,
    `Attention is all you need`,
    `I hope everyone can lead meaningful lives and do whatever that makes them happy, because after all, it is YOUR life. Not all of us have to become doctors, lawyers, wealthy businesspersons, or get married to be happy. I just wish I could say this to my late friend.`,
    `Thoughts are distinct from consciousness – you cannot steer your thoughts anymore that you can dictate what noise your ears will hear next. There seems to be a random process going on, totally un-called-for thoughts entering your consciousness. Sometimes a thought pops up, and comes an adjunct of other bodily feelings. So it seems as if the arising of thoughts is connected with the physical body on some level. The same goes for emotions.`,
    `Shaping the outputs of a random number generator is a great way of getting into new territory, but so is just working with the material (whether clay or code) and seeing where it takes you. It is all just a creative feedback loop.`,
    `Why repeat the past?`,
    `It is a misunderstanding of creativity that creators are geniuses that are projecting from a perfect world of ideas into reality. But what really happens with making is that we start making something, but then respond to the material, and end up with something quite different that our original idea.`,
    `The emergence of live coding was in part a reaction against “generative art”, in particular the idea that by using random numbers, we can create infinite variation, and gasp at the creative system we’ve made that hods a mirror to the beauty of the system. The problem is that the more we listen to infinite variation, the more it sounds the same.`,
    `It is not worthwhile to think of what you haven't or could have done. The best we can do is to enjoy the present moment.`,
    `A curve is not composed of points, it is a law that points obey, or again, a law according to which points can be constructed.`,
    `Seeing Like a State: To the planner, an orderly place is a place that looks orderly."`,
    `Some artists simply surrender to the unconscious.`,
    `In this distorted view, there's still belief in the dichotomy of self and others (and therefore the lack of others is experienced as loneliness), and the passing of time (and therefore the loneliness lasting forever). Both time and self are still division, while the truth is more fundamental than any division. I think the recognition of this truth is hellish to the extent that you still cling to division, and blissful to the extent that you can let go of it. To interpret an infinite consciousness as lonely is still to project your separateness from everything else.`,
    `...he says to me, "Are you ready to be yourself again?" I said, "Which one?"`,
    "I dream in yellow",
    "I do not know what I may appear to the world, but to myself I seem to have been only like a boy playing on the sea-shore, and diverting myself in now and then finding a smoother pebble or a prettier shell than ordinary, whilst the great ocean of truth lay all undiscovered before me",
    "Perhaps someone is amazed when he has read these books, but no one more than I when I turn around now (after having been an author for seven years and just as if in one breath) and look at what has been accomplished and with almost a shiver of amazement see that the whole thing is actually only one thought.",
    "Here I stand, I can do no other, so help me God",
    "I love the stillness that gets interrupted by the wind bristling through the leaves in the trees. I love the sound of big windchimes. I love life.",
    "Just pilot the robot Shinji",
    "The void which binds",
    "Existence over essence",
    "Whose Justice? Which Rationality?",
    "Do something again and again from morning till evening, and to dream of it at night, and to think of nothing else than doing this well, as well as I alone can. When one lives this way, one thing after another that does not belong to such a life drops off, without hate or reluctance. What we do should determine what we forego.",
    "Never approach stories one at a time. If one writes a story at time, one can end up writing the same story until one dies. It is best to write them three, or five at a time. More if you have the energy. Don't write two at a time either: their interplay, like lovers' mirrors,  produces melancholy.",
    "Sphinx of black quartz, judge my vow",
    "If one says 'red' and there are 50 people listening, one can be sure that there will arise 50 different reds in the 50 different minds",
];
